### ISSUE TITLE
Charter Feedback

### ISSUE THREAD

**Issue by nadalin** [hlflanagan/fedidcg#6]
Seems odd to have a charter that deals with authentication and not have a coordination with the the WebAuthn WG, as this is the only W3C WG dealing with secure authentication, suggest you add the WebAuthn WG especially if this WG takes up roaming type (cloud based) authentication,

OpenID Connect was listed but it maybe worth calling out OpenID Connect Federation 1.0 specifically

**Comment by jaredhanson** [comment]
It's worth noting that that [Web Authentication](https://www.w3.org/TR/webauthn-2/) builds upon [Credential Management](https://w3c.github.io/webappsec-credential-management/), but that the two specs have different working groups, [WebAuthn](https://www.w3.org/Webauthn/) and [WebAppSec](https://www.w3.org/2011/webappsec/), respectively.

I suspect that WebAuthn falls out of scope, since it is not a federated authentication technology.  However, Credential Management defines [federated credentials](https://www.w3.org/TR/credential-management-1/#federated), so there should be coordination and alignment there.

**Comment by nadalin** [comment]
> It's worth noting that that [Web Authentication](https://www.w3.org/TR/webauthn-2/) builds upon [Credential Management](https://w3c.github.io/webappsec-credential-management/), but that the two specs have different working groups, [WebAuthn](https://www.w3.org/Webauthn/) and [WebAppSec](https://www.w3.org/2011/webappsec/), respectively.
> 
> I suspect that WebAuthn falls out of scope, since it is not a federated authentication technology. However, Credential Management defines [federated credentials](https://www.w3.org/TR/credential-management-1/#federated), so there should be coordination and alignment there.

Federated identity is out of scope for WebAuthn, but that does not mean that Federated Authentication is out of scope. WebAuthn only uses the CredMan Class, so I would not say that is builds upon.

**Comment by hlflanagan** [comment]
Listing these seems reasonable. Added.
